export const programsData = [
	{
		id: 0,
		src: "/img/ourPrograms/image_big_1.png",
		src_mob: "/img/ourPrograms/image_mob_1.png",
		titleKey: "cart_1.cart_name",
		localKey: "cart_1.local",
		dateKey: "cart_1.date",
		descrKey: "cart_1.description_event",
		drone_1_nameKey: "cart_1.drone_1.name",
		drone_1_for_useKey: "cart_1.drone_1.for_use",
		drone_2_nameKey: "cart_1.drone_2.name",
		drone_2_for_useKey: "cart_1.drone_2.for_use",
	},
	{
		id: 1,
		src: "/img/ourPrograms/image_big_2.png",
		src_mob: "/img/ourPrograms/image_mob_2.png",
		titleKey: "cart_2.cart_name",
		localKey: "cart_2.local",
		dateKey: "cart_2.date",
		descrKey: "cart_2.description_event",
		drone_1_nameKey: "cart_2.drone_1.name",
		drone_1_for_useKey: "cart_2.drone_1.for_use",
		drone_2_nameKey: "cart_2.drone_2.name",
		drone_2_for_useKey: "cart_2.drone_2.for_use",
	},
	{
		id: 2,
		src: "/img/ourPrograms/image_big_3.png",
		src_mob: "/img/ourPrograms/image_mob_3.png",
		titleKey: "cart_3.cart_name",
		localKey: "cart_3.local",
		dateKey: "cart_3.date",
		descrKey: "cart_3.description_event",
		drone_1_nameKey: "cart_3.drone_1.name",
		drone_1_for_useKey: "cart_3.drone_1.for_use",
		drone_2_nameKey: "cart_3.drone_2.name",
		drone_2_for_useKey: "cart_3.drone_2.for_use",
	},
	{
		id: 3,
		src: "/img/ourPrograms/image_big_1.png",
		src_mob: "/img/ourPrograms/image_mob_1.png",
		titleKey: "cart_4.cart_name",
		localKey: "cart_4.local",
		dateKey: "cart_4.date",
		descrKey: "cart_4.description_event",
		drone_1_nameKey: "cart_4.drone_1.name",
		drone_1_for_useKey: "cart_4.drone_1.for_use",
		drone_2_nameKey: "cart_4.drone_2.name",
		drone_2_for_useKey: "cart_4.drone_2.for_use",
	},
	{
		id: 4,
		src: "/img/ourPrograms/image_big_2.png",
		src_mob: "/img/ourPrograms/image_mob_2.png",
		titleKey: "cart_5.cart_name",
		localKey: "cart_5.local",
		dateKey: "cart_5.date",
		descrKey: "cart_5.description_event",
		drone_1_nameKey: "cart_5.drone_1.name",
		drone_1_for_useKey: "cart_5.drone_1.for_use",
		drone_2_nameKey: "cart_5.drone_2.name",
		drone_2_for_useKey: "cart_5.drone_2.for_use",
	},
	{
		id: 5,
		src: "/img/ourPrograms/image_big_3.png",
		src_mob: "/img/ourPrograms/image_mob_3.png",
		titleKey: "cart_6.cart_name",
		localKey: "cart_6.local",
		dateKey: "cart_6.date",
		descrKey: "cart_6.description_event",
		drone_1_nameKey: "cart_6.drone_1.name",
		drone_1_for_useKey: "cart_6.drone_1.for_use",
		drone_2_nameKey: "cart_6.drone_2.name",
		drone_2_for_useKey: "cart_6.drone_2.for_use",
	},
];
